[package]
name = "sqlx_setup"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
dotenvy = "0.15.7"
googletest = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
sqlx = { workspace = true }
tokio = { workspace = true }
dotenvy = "0.15.7"
