[package]
name = "ctr"
version = "0.1.0"
edition = "2021"

[dependencies]
fs-err = "2.11.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.27"
serde_json = "1.0.108"
anyhow = "1.0.75"
pretty_assertions = "1.4.0"
owo-colors = "3"
regex = "1.10.2"
once_cell = "1.19.0"
textwrap = "0.16.0"